"""empty message

Revision ID: 3502d79ab1c6
Revises: c6764cff4979
Create Date: 2018-06-17 22:32:19.822478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3502d79ab1c6'
down_revision = 'c6764cff4979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
